default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Correcamino@1
  host: localhost
  pool: 5

development:
  <<: *default
  database: simuladorimpacto_development

test:
  <<: *default
  database: simuladorimpacto_test

production:
  <<: *default
  database: simuladorimpacto_production
  username: simuladorimpacto
  password: <%= ENV["SIMULADORIMPACTO_DATABASE_PASSWORD"] %>
